name: deep_animator
channels:
- pytorch
- defaults
dependencies:
- jupyter
- pytorch
- imageio
- numpy
- matplotlib
- pandas
- Pillow
- scikit-image
- scikit-learn
- scipy
- pip
- tqdm
- fire
- ffmpeg
